export enum EmbedMessage {
  PING = "PING",
  MOUNT = "MOUNT",
  HAPTIC = "HAPTIC",
  CAMERA = "CAMERA",
  SHEET_MOUNTED = "SHEET_MOUNTED",
  CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS",
  MENU_ITEM_SELECTED = "MENU_ITEM_SELECTED",
  RESTORE_PURCHASE = "RESTORE_PURCHASE",
  CHECK_SUBSCRIPTION = "CHECK_SUBSCRIPTION",
  MODIFY_SUBSCRIPTION = "MODIFY_SUBSCRIPTION",
  LOCATION = "LOCATION",
  TRANSCRIBE_AUDIO = "TRANSCRIBE_AUDIO",
  RETRIEVE_JOB = "RETRIEVE_JOB",
  DOWNLOAD_MODEL = "DOWNLOAD_MODEL"
}

export enum EmbedDataMessage {
  BG = "bg",
  COLORS = "colorscheme",
  ROOT_FONT_SIZE = "rootFontSize",
  MODAL = "modal",
  PURCHASE = "purchase",
  MESSAGE = "message",
  DATA = "data",
  FILE = "file",
  FETCH = "fetch",
  DOWNLOAD = "download",
  RELOAD = "reload",
  ERROR = "error",
  NOTIFICATIONS = "notifications",
  ACCOUNT = "account",
  AUTHFN_NATIVE_HANDOFF = "authfn.nativeHandoffRequested",
  AUTHFN_NATIVE_APPLE_SIGN_IN = "authfn.nativeAppleSignInRequested",
  AUTHFN_SIGN_OUT = "authfn.signOut",
  OAUTH = "oauth",
  LINK = "link",
  LOG = "log",
  ENABLE_GESTURE_NAVIGATION = "enableGestureNavigation"
}
