export enum TranscriptionModel {
  TINY_EN = "Xenova/whisper-tiny.en",
  SMALL_EN = "Xenova/whisper-small.en",
  BASE_EN = "Xenova/whisper-base.en",
  MEDIUM_EN = "Xenova/whisper-medium.en",
  DISTILL_SMALL_EN = "distil-whisper/distil-small.en"
}

export enum TacoActions {
  INITIALIZE_TRANSCRIBER,
  RESET_TRANSCRIBER,
  GET_TRANSCRIPTION,
  INITIALIZE_FEATURE_EXTRACTOR,
  RESET_FEATURE_EXTRACTOR,
  GET_EMBEDDINGS,
  GEN_EMBEDDINGS_AND_RETURN_PROCESSED_DATA,
  INITIALIZE_QUESTION_ANSWERER,
  RESET_QUESTION_ANSWERER,
  GET_ANSWER,
  INITIALIZE_TEXT2TEXT_GENERATOR,
  RESET_TEXT2TEXT_GENERATOR,
  T2TGENERATE_TEXT,
  INITIALIZE_TEXT_GENERATOR,
  RESET_TEXT_GENERATOR,
  GENERATE_TEXT
}

export enum TacoLocalAIOptions {
  SEMANTIC_SEARCH = "semanticSearch",
  AUDIO_TRANSCRIPTION = "audioTranscription",
  MARKDOWN_QA = "markdownQA"
}
