/** Stable node content identifiers shared by storage, rendering and memory capabilities. */
export enum NodeType {
  UNKNOWN = "UNKNOWN",
  NODULAR_MARKDOWN = "NODULAR_MARKDOWN",
  NON_NODULAR_MARKDOWN = "NON_NODULAR_MARKDOWN",

  //TEXT
  HEADING1 = "HEADING1",
  HEADING2 = "HEADING2",
  HEADING3 = "HEADING3",
  HEADING4 = "HEADING4",
  HEADING5 = "HEADING5",
  SIMPLE_TEXT = "SIMPLE_TEXT",
  QUOTE = "QUOTE",
  CODE = "CODE",
  LATEX = "LATEX",
  CALLOUT = "CALLOUT",
  LINK = "LINK",

  //List types
  LIST = "LIST",
  ORDERED_LIST = "ORDERED_LIST",
  CHECKLIST = "CHECKLIST",

  //MEDIA
  IMAGE = "IMAGE",
  AUDIO = "AUDIO",
  VIDEO = "VIDEO",
  PDF = "PDF",
  FILE = "FILE",
  SKETCH = "SKETCH",

  //EMBED
  EMBED = "EMBED",
  TOC = "TOC",
  NODE_AS_EMBED = "NODE_AS_EMBED",
  COLLECTION_AS_EMBED = "COLLECTION_AS_EMBED",
  TASK_AS_EMBED = "TASK_AS_EMBED",
  GRAPH_AS_EMBED = "GRAPH_AS_EMBED",
  CALENDAR_AS_EMBED = "CALENDAR_AS_EMBED",
  TREE_OF_LINKS = "TREE_OF_LINKS",
  GIST = "GIST",

  //LAYOUT
  DIVIDER = "DIVIDER",
  DOUBLE_DIVIDER = "DOUBLE_DIVIDER",
  TABLE = "TABLE",
  STACK = "STACK",
  MEDIA_GRID = "MEDIA_GRID",
  COLUMNS = "COLUMNS",
  TABS = "TABS",
  CARDS = "CARDS",
  ACCORDION = "ACCORDION",

  //BOOKMARKS
  /**
   * Legacy support - Used "PDF_CLIP" as value until Memotron v0.62
   */
  PDF_BOOKMARK = "PDF_CLIP",
  AUDIO_BOOKMARK = "AUDIO_BOOKMARK",
  VIDEO_BOOKMARK = "VIDEO_BOOKMARK",
  /**
   * Legacy support - Used "TEXT_CLIP" as value until Memotron v0.62
   */
  WEB_TEXT_BOOKMARK = "TEXT_CLIP",
  /**
   * Legacy support - Used "WEB_SCREENSHOT_CLIP" as value until Memotron v0.62
   */
  WEB_SCREENSHOT = "WEB_SCREENSHOT_CLIP",
  KINDLE_HIGHLIGHT = "KINDLE_HIGHLIGHT",
  /**
   * Legacy support - Used "YOUTUBE_TIMESTAMP_CLIP" as value until Memotron v0.62
   */
  YOUTUBE_BOOKMARK = "YOUTUBE_TIMESTAMP_CLIP",
  /**
   * Used for all video timestamp bookmarks on all other platforms other than Youtube
   */
  WEB_VIDEO_BOOKMARK = "WEB_VIDEO_BOOKMARK",

  //EXTERNAL
  WEB_PAGE = "WEB_PAGE",
  KINDLE_BOOK = "KINDLE_BOOK",

  //SOCIAL
  TWEET = "TWEET",
  TWITTER_PROFILE = "TWITTER_PROFILE",
  MASTODON_POST = "MASTODON_POST",
  MASTODON_PROFILE = "MASTODON_PROFILE",
  BLUESKY_POST = "BLUESKY_POST",
  BLUESKY_PROFILE = "BLUESKY_PROFILE",
  THREADS_POST = "THREADS_POST",
  THREADS_PROFILE = "THREADS_PROFILE",
  LINKEDIN_POST = "LINKEDIN_POST",
  LINKEDIN_PROFILE = "LINKEDIN_PROFILE",
  LINKEDIN_GROUP = "LINKEDIN_GROUP",
  INSTAGRAM_POST = "INSTAGRAM_POST",
  INSTAGRAM_REEL = "INSTAGRAM_REEL",
  INSTAGRAM_PROFILE = "INSTAGRAM_PROFILE",
  FACEBOOK_POST = "FACEBOOK_POST",
  FACEBOOK_PROFILE = "FACEBOOK_PROFILE",
  FACEBOOK_GROUP = "FACEBOOK_GROUP",
  REDDIT_POST = "REDDIT_POST",
  REDDIT_PROFILE = "REDDIT_PROFILE",
  REDDIT_SUB = "REDDIT_SUB",
  DISCORD_THREAD = "DISCORD_THREAD",

  //WEB VIDEO
  YOUTUBE_VIDEO = "YOUTUBE_VIDEO",
  YOUTUBE_SHORT = "YOUTUBE_SHORT",
  YOUTUBE_CHANNEL = "YOUTUBE_CHANNEL",
  COURSERA_VIDEO = "COURSERA_VIDEO",
  UDEMY_VIDEO = "UDEMY_VIDEO",
  EDX_VIDEO = "EDX_VIDEO",
  SKILLSHARE_VIDEO = "SKILLSHARE_VIDEO",
  VIMEO_VIDEO = "VIMEO_VIDEO",
  RUMBLE_VIDEO = "RUMBLE_VIDEO",
  INSTRUCTURE_VIDEO = "INSTRUCTURE_VIDEO",
  KHAN_VIDEO = "KHAN_VIDEO",
  MOODLE_VIDEO = "MOODLE_VIDEO",
  TED_VIDEO = "TED_VIDEO",
  TWITCH_STREAM = "TWITCH_STREAM",

  //OTHER WEB
  STACKOVERFLOW_THREAD = "STACKOVERFLOW_THREAD",
  GITHUB_REPO = "GITHUB_REPO",
  GITHUB_PROFILE = "GITHUB_PROFILE",
  GITHUB_DISCUSSION = "GITHUB_DISCUSSION",
  GITLAB_PROJECT = "GITLAB_PROJECT"
}
